
package GUI;

import plazavea.solicitudseguro.Repositorio;
import plazavea.solicitudseguro.SolicitudSeguroSalud;
import plazavea.solicitudseguro.SolicitudSeguroSalud2;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.stream.Collectors;
import java.util.List;
import java.util.Optional;


public class JFrame_gestorsolisitud extends javax.swing.JFrame {

   private Repositorio repositorio;
    private DefaultTableModel tableModel;
    private int nextId = 1;
    
    
    public JFrame_gestorsolisitud() {
        initComponents();
        repositorio = new Repositorio();
        initializeTable();
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbsolicitud = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btbuscar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbsolicitud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "APELLIDO", "TIPO DE SOLICITUD", "FECHA DE SOLICITUD", "ESTADO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbsolicitud);

        titulo.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        titulo.setText("GESTOR DE SOLICITUDES ");

        regresar.setText("REGRESAR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        jLabel3.setText("ID SOLICITUD:");

        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });

        btbuscar.setText("BUSCAR");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btbuscar)
                            .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titulo)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Eliminar)
                    .addComponent(btbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regresar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void initializeTable() {
        tableModel = new DefaultTableModel(new String[]{"ID", "Tipo", "Nombre", "Fecha"}, 0);
        tbsolicitud.setModel(tableModel);
    }
    
    private void populateTable() {
        tableModel.setRowCount(0);

        // Get all stored solicitudes
        List<SolicitudSeguroSalud> saludSolicitudes = repositorio.getSolicitudesSalud();
        List<SolicitudSeguroSalud2> salud2Solicitudes = repositorio.getSolicitudesSalud2();

        // Add Salud solicitudes
        for (SolicitudSeguroSalud s : saludSolicitudes) {
            tableModel.addRow(new Object[]{nextId++, "Salud", s.getNombre(), s.getFecha()});
        }

        // Add Salud2 solicitudes
        for (SolicitudSeguroSalud2 s : salud2Solicitudes) {
            tableModel.addRow(new Object[]{nextId++, "Salud2", s.getNombreConyuge(), s.getFechaFinVinculo()});
        }
    }
     private void buscarSolicitud(String buscar) {
        // Clear table
        tableModel.setRowCount(0);

        // Search in Salud solicitudes
        for (SolicitudSeguroSalud s : repositorio.getSolicitudesSalud()) {
            if (s.getNombre().toLowerCase().contains(buscar.toLowerCase())) {
                tableModel.addRow(new Object[]{s.getId(), "Salud", s.getNombre(), s.getFecha()});
            }
        }

        // Search in Salud2 solicitudes
        for (SolicitudSeguroSalud2 s : repositorio.getSolicitudesSalud2()) {
            if (s.getNombreConyuge().toLowerCase().contains(buscar.toLowerCase())) {
                tableModel.addRow(new Object[]{s.getId(), "Salud2", s.getNombreConyuge(), s.getFechaFinVinculo()});
            }
        }
    }
    
     private void eliminarSolicitud() {
        int selectedRow = tbsolicitud.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (int) tableModel.getValueAt(selectedRow, 0);
            String tipo = (String) tableModel.getValueAt(selectedRow, 1);

            if (tipo.equals("Salud")) {
                eliminarSolicitudSalud(id);
            } else if (tipo.equals("Salud2")) {
                eliminarSolicitudSalud2(id);
            }

            tableModel.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una solicitud para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
     
     private void eliminarSolicitudSalud(int id) {
         Optional<SolicitudSeguroSalud> solicitud = repositorio.getSolicitudesSalud().stream()
                .filter(s -> s.getId() == id)
                .findFirst();

        solicitud.ifPresent(s -> repositorio.getSolicitudesSalud().remove(s));
    }
      private void eliminarSolicitudSalud2(int id) {
        Optional<SolicitudSeguroSalud2> solicitud = repositorio.getSolicitudesSalud2().stream()
                .filter(s -> s.getId() == id)
                .findFirst();

        solicitud.ifPresent(s -> repositorio.getSolicitudesSalud2().remove(s));
    }
     
    
    
    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        JFrame_Menu menu = new JFrame_Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
            buscarSolicitud(txt_buscar.getText());
    
        
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
       buscarSolicitud(txt_buscar.getText());
    
    }//GEN-LAST:event_btbuscarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
         eliminarSolicitud();
    
    }//GEN-LAST:event_btn_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_gestorsolisitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_gestorsolisitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_gestorsolisitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_gestorsolisitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_gestorsolisitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton regresar;
    private javax.swing.JTable tbsolicitud;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables

    
}
