/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author KB
 */
public class JFrame_Empleados extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Empleados
     */
    public JFrame_Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaempleados = new javax.swing.JTable();
        botonregistrarempleado = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        botonmodificar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("EMPLEADOS ");

        tablaempleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(442424), "LUIS", "LOPES",  new Integer(21), null, null, null, null, null},
                { new Integer(242424), "MARIA", "LOPEZ",  new Integer(21), null, null, null, null, null},
                { new Integer(242424), "JOSE", "GUITIERRES",  new Integer(32), null, null, null, null, null},
                { new Integer(2424244), "RODRIGO", "ROMERO",  new Integer(45), null, null, null, null, null},
                { new Integer(564564), "MIGUEL", "FLORES",  new Integer(44), null, null, null, null, null},
                { new Integer(6755), "HELEN", "GULLEROMO",  new Integer(21), null, null, null, null, null},
                { new Integer(45556), "LUISA", "TORRES",  new Integer(23), null, null, null, null, null},
                { new Integer(4564645), "PEPE", "ALTARES",  new Integer(22), null, null, null, null, null},
                { new Integer(221243), "GAEL", "SETMIS",  new Integer(32), null, null, null, null, null},
                { new Integer(2424), "LEO", "TAMMA",  new Integer(23), null, null, null, null, null},
                { new Integer(324234), "ETTO", "EWER",  new Integer(42), null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellidos", "Edad", "Genero", "DNI", "Telefono", "Puesto", "Tipo de Seguro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaempleados.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaempleados);
        tablaempleados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        botonregistrarempleado.setText("REGISTRAR NUEVO EMPLEADO");
        botonregistrarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregistrarempleadoActionPerformed(evt);
            }
        });

        botoneliminar.setText("ELIMINAR");

        botonmodificar.setText("MODIFICAR");

        atras.setText("ATRAS");

        botonBuscar.setText("BUSCAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(botonBuscar)
                .addGap(55, 55, 55)
                .addComponent(botonmodificar)
                .addGap(35, 35, 35)
                .addComponent(botoneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(botonregistrarempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(atras)
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonregistrarempleado)
                        .addComponent(botoneliminar)
                        .addComponent(botonmodificar)
                        .addComponent(atras)
                        .addComponent(botonBuscar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonregistrarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregistrarempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonregistrarempleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton botonmodificar;
    private javax.swing.JButton botonregistrarempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaempleados;
    // End of variables declaration//GEN-END:variables
}
